/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`chainstate_height_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChainstateHeightOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`chainstate_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChainstateOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`deposit_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DepositOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`deposit_recipient_recipient_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DepositRecipientRecipientOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`deposit_reclaim_pubkeys_reclaim_pubkeys_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DepositReclaimPubkeysReclaimPubkeysOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`deposit_txid_index_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DepositTxidIndexOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`deposit_txid_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DepositTxidOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`health_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HealthOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`limits_account_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LimitsAccountOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`limits_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LimitsOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`start_throttle_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StartThrottleOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`withdrawal_id_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WithdrawalIdOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`withdrawal_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WithdrawalOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`withdrawal_recipient_recipient_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WithdrawalRecipientRecipientOptionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`withdrawal_sender_sender_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WithdrawalSenderSenderOptionsError {
    UnknownValue(serde_json::Value),
}

/// Handles CORS preflight requests
pub async fn chainstate_height_options(
    configuration: &configuration::Configuration,
    height: u64,
) -> Result<(), Error<ChainstateHeightOptionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_height = height;

    let uri_str = format!(
        "{}/chainstate/{height}",
        configuration.base_path,
        height = p_path_height
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ChainstateHeightOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn chainstate_options(
    configuration: &configuration::Configuration,
) -> Result<(), Error<ChainstateOptionsError>> {
    let uri_str = format!("{}/chainstate", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ChainstateOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn deposit_options(
    configuration: &configuration::Configuration,
) -> Result<(), Error<DepositOptionsError>> {
    let uri_str = format!("{}/deposit", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DepositOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn deposit_recipient_recipient_options(
    configuration: &configuration::Configuration,
    recipient: &str,
) -> Result<(), Error<DepositRecipientRecipientOptionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_recipient = recipient;

    let uri_str = format!(
        "{}/deposit/recipient/{recipient}",
        configuration.base_path,
        recipient = crate::apis::urlencode(p_path_recipient)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DepositRecipientRecipientOptionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn deposit_reclaim_pubkeys_reclaim_pubkeys_options(
    configuration: &configuration::Configuration,
    reclaim_pubkeys: &str,
) -> Result<(), Error<DepositReclaimPubkeysReclaimPubkeysOptionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_reclaim_pubkeys = reclaim_pubkeys;

    let uri_str = format!(
        "{}/deposit/reclaim-pubkeys/{reclaimPubkeys}",
        configuration.base_path,
        reclaimPubkeys = crate::apis::urlencode(p_path_reclaim_pubkeys)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DepositReclaimPubkeysReclaimPubkeysOptionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn deposit_txid_index_options(
    configuration: &configuration::Configuration,
    txid: &str,
    index: &str,
) -> Result<(), Error<DepositTxidIndexOptionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_txid = txid;
    let p_path_index = index;

    let uri_str = format!(
        "{}/deposit/{txid}/{index}",
        configuration.base_path,
        txid = crate::apis::urlencode(p_path_txid),
        index = crate::apis::urlencode(p_path_index)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DepositTxidIndexOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn deposit_txid_options(
    configuration: &configuration::Configuration,
    txid: &str,
) -> Result<(), Error<DepositTxidOptionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_txid = txid;

    let uri_str = format!(
        "{}/deposit/{txid}",
        configuration.base_path,
        txid = crate::apis::urlencode(p_path_txid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DepositTxidOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn health_options(
    configuration: &configuration::Configuration,
) -> Result<(), Error<HealthOptionsError>> {
    let uri_str = format!("{}/health", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<HealthOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn limits_account_options(
    configuration: &configuration::Configuration,
    account: &str,
) -> Result<(), Error<LimitsAccountOptionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_account = account;

    let uri_str = format!(
        "{}/limits/{account}",
        configuration.base_path,
        account = crate::apis::urlencode(p_path_account)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<LimitsAccountOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn limits_options(
    configuration: &configuration::Configuration,
) -> Result<(), Error<LimitsOptionsError>> {
    let uri_str = format!("{}/limits", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<LimitsOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn start_throttle_options(
    configuration: &configuration::Configuration,
) -> Result<(), Error<StartThrottleOptionsError>> {
    let uri_str = format!("{}/start_throttle", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<StartThrottleOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn withdrawal_id_options(
    configuration: &configuration::Configuration,
    id: u64,
) -> Result<(), Error<WithdrawalIdOptionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!(
        "{}/withdrawal/{id}",
        configuration.base_path,
        id = p_path_id
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<WithdrawalIdOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn withdrawal_options(
    configuration: &configuration::Configuration,
) -> Result<(), Error<WithdrawalOptionsError>> {
    let uri_str = format!("{}/withdrawal", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<WithdrawalOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn withdrawal_recipient_recipient_options(
    configuration: &configuration::Configuration,
    recipient: &str,
) -> Result<(), Error<WithdrawalRecipientRecipientOptionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_recipient = recipient;

    let uri_str = format!(
        "{}/withdrawal/recipient/{recipient}",
        configuration.base_path,
        recipient = crate::apis::urlencode(p_path_recipient)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<WithdrawalRecipientRecipientOptionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Handles CORS preflight requests
pub async fn withdrawal_sender_sender_options(
    configuration: &configuration::Configuration,
    sender: &str,
) -> Result<(), Error<WithdrawalSenderSenderOptionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_sender = sender;

    let uri_str = format!(
        "{}/withdrawal/sender/{sender}",
        configuration.base_path,
        sender = crate::apis::urlencode(p_path_sender)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<WithdrawalSenderSenderOptionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
