/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DepositStatus : The status of the in-flight sBTC deposit.
/// The status of the in-flight sBTC deposit.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DepositStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "reprocessing")]
    Reprocessing,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "confirmed")]
    Confirmed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "rbf")]
    Rbf,
}

impl std::fmt::Display for DepositStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pending => write!(f, "pending"),
            Self::Reprocessing => write!(f, "reprocessing"),
            Self::Accepted => write!(f, "accepted"),
            Self::Confirmed => write!(f, "confirmed"),
            Self::Failed => write!(f, "failed"),
            Self::Rbf => write!(f, "rbf"),
        }
    }
}

impl Default for DepositStatus {
    fn default() -> DepositStatus {
        Self::Pending
    }
}
