/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DepositWithStatus : Wrapper for deposit with status code. Used for multi-status responses.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DepositWithStatus {
    #[serde(rename = "deposit")]
    pub deposit: Box<models::Deposit>,
    /// HTTP status code, returned as part of multi-status responses.
    #[serde(rename = "status")]
    pub status: u32,
}

impl DepositWithStatus {
    /// Wrapper for deposit with status code. Used for multi-status responses.
    pub fn new(deposit: models::Deposit, status: u32) -> DepositWithStatus {
        DepositWithStatus {
            deposit: Box::new(deposit),
            status,
        }
    }
}
