/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExpectedFulfillmentInfo : Expected information about future fulfillment of the withdrawal. This struct represents _estimate_ of how fulfillment for the withdrawal will look like. This estimation is for reference only, and does not provide any guarantees.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpectedFulfillmentInfo {
    /// Expected bitcoin block height into which sweep transaction will be included into the block.
    #[serde(
        rename = "expectedHeight",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expected_height: Option<Option<u64>>,
    /// Expected txid of the sweep transaction.
    #[serde(
        rename = "expectedTxid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expected_txid: Option<Option<String>>,
}

impl ExpectedFulfillmentInfo {
    /// Expected information about future fulfillment of the withdrawal. This struct represents _estimate_ of how fulfillment for the withdrawal will look like. This estimation is for reference only, and does not provide any guarantees.
    pub fn new() -> ExpectedFulfillmentInfo {
        ExpectedFulfillmentInfo {
            expected_height: None,
            expected_txid: None,
        }
    }
}
