/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetThrottleKeyResponse : Response to get_throttle_key endpoint, with information about the key
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetThrottleKeyResponse {
    /// The hash of the key.
    #[serde(rename = "hash")]
    pub hash: String,
    /// If this key is eligible to start throttle mode.
    #[serde(rename = "isActive")]
    pub is_active: bool,
    /// The name of the key.
    #[serde(rename = "name")]
    pub name: String,
}

impl GetThrottleKeyResponse {
    /// Response to get_throttle_key endpoint, with information about the key
    pub fn new(hash: String, is_active: bool, name: String) -> GetThrottleKeyResponse {
        GetThrottleKeyResponse { hash, is_active, name }
    }
}
