/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ThrottleRequest : Represents the throttle reqwest
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThrottleRequest {
    /// The name of the key.
    #[serde(rename = "name")]
    pub name: String,
    /// The secret associated with this key.
    #[serde(rename = "secret")]
    pub secret: String,
}

impl ThrottleRequest {
    /// Represents the throttle reqwest
    pub fn new(name: String, secret: String) -> ThrottleRequest {
        ThrottleRequest { name, secret }
    }
}
