/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ThrottleKey : Represents the throttle key
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThrottleKey {
    /// The name of the key.
    #[serde(rename = "name")]
    pub name: String,
    /// The secret of the secret associated with this key.
    #[serde(rename = "secret")]
    pub secret: String,
}

impl ThrottleKey {
    /// Represents the throttle key
    pub fn new(name: String, secret: String) -> ThrottleKey {
        ThrottleKey { name, secret }
    }
}
