services:

  bitcoind:
    container_name: bitcoind
    image: bitcoin/bitcoin:25.2@sha256:14b4777166cba8de36b62ce72801038760a8f490122781b66d40592c8c69ebda
    volumes:
      - ../signer/tests/service-configs/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    restart: on-failure
    # For some reason, the CMD in the original Dockerfile is set to publish
    # events on zeromq, and it seems to interfere with the events that we
    # want to publish. So we overwrite the CMD by just setting the
    # -logtimestamps argument in the command here.
    command: [ "-logtimestamps" ]
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        bitcoind
    stop_grace_period: 10s
    ports:
      - "127.0.0.1:18443:18443"
      - "127.0.0.1:28332:28332"
    healthcheck:
      test: [ "CMD-SHELL", "bitcoin-cli getblockcount" ]
      interval: 3s
      timeout: 1s
      retries: 3

  postgres:
    image: postgres:16.6-bookworm@sha256:c965017e1d29eb03e18a11abc25f5e3cd78cb5ac799d495922264b8489d5a3a1
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=postgres --dbname=signer" ]
      interval: 2s
      timeout: 1s
      retries: 5

  # DynamoDB Tables for the Emily API.
  emily-dynamodb:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    ports:
      - "127.0.0.1:8000:8000"

  # Modifies Emily's CDK template and creates DynamoDB Tables.
  emily-aws-setup:
    build:
      context: ../
      dockerfile: docker/sbtc/Dockerfile
      target: emily-aws-setup
    depends_on:
      - emily-dynamodb
    environment:
      - DYNAMODB_ENDPOINT=http://emily-dynamodb:8000
      - DEPLOYER_ADDRESS=

  # Runs the Emily server.
  emily-server:
    build:
      context: ../
      dockerfile: docker/sbtc/Dockerfile
      target: emily-server
      args:
        EMILY_SERVER_BUILD_ARGS: --features testing
    depends_on:
      emily-aws-setup:
        condition: service_completed_successfully
    environment:
      - DYNAMODB_ENDPOINT=http://emily-dynamodb:8000
      - AWS_ACCESS_KEY_ID=xxxxxxxxxxxx
      - AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxx
      - AWS_REGION=us-west-2
      - PORT=3031
    ports:
      - "127.0.0.1:3031:3031"
