
# cargo-vet audits file

[[audits.argon2]]
who = "viktar <mcviktor@tut.by"
criteria = "safe-to-deploy"
version = "0.5.3"

[[audits.bitcoinconsensus]]
who = "cylewitruk <cyle.witruk@outlook.com>"
criteria = "safe-to-deploy"
version = "0.106.0+26.0"
notes = """
I have reviewed both bitcoinconsensus and sys-libbitcoinconsensus which it uses to build the relevant bitcoin-core sources.
The bitcoin-core sources are indeed from bitcoin-core v26.
Note that this library does use C bindings and thus FFI and unsafe. There are panic-able code paths if used incorrectly.
This library is provided by the rust-bitcoin GH organization which also maintains the bitcoin and secp256k1 crates which we use extensively.
"""

[[audits.hashbrown]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.16.0 -> 0.16.1"

[[audits.httparse]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.8.0 -> 1.10.1"

[[audits.hyper]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.5.1 -> 1.8.1"

[[audits.libp2p-allow-block-list]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.5.0 -> 0.6.0"

[[audits.libp2p-autonat]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.14.0 -> 0.15.0"

[[audits.libp2p-connection-limits]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.5.0 -> 0.6.0"

[[audits.libp2p-core]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.43.0 -> 0.43.2"

[[audits.libp2p-identify]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.46.0 -> 0.47.0"

[[audits.libp2p-identity]]
who = "cylewitruk <cyle.witruk@outlook.com>"
criteria = "safe-to-deploy"
delta = "0.2.10 -> 0.2.12"
notes = "This patch switches to k256 from libsecp256k1 for secp256k1 handling"

[[audits.libp2p-identity]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.12 -> 0.2.13"

[[audits.libp2p-metrics]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.16.0 -> 0.17.0"

[[audits.libp2p-noise]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.46.0 -> 0.46.1"

[[audits.libp2p-ping]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.46.0 -> 0.47.0"

[[audits.libp2p-quic]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.12.0 -> 0.13.0"

[[audits.libp2p-swarm]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.46.0 -> 0.47.1"

[[audits.libp2p-swarm-derive]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.35.0 -> 0.35.1"

[[audits.libp2p-tls]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.6.0 -> 0.6.2"

[[audits.libp2p-upnp]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.4.0 -> 0.5.0"

[[audits.libsecp256k1]]
who = "cylewitruk <cyle.witruk@outlook.com>"
criteria = "safe-to-deploy"
delta = "0.7.1 -> 0.7.2"

[[audits.metrics-exporter-prometheus]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.16.1 -> 0.18.1"

[[audits.metrics-util]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.19.0 -> 0.20.1"

[[audits.oid-registry]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.7.1 -> 0.8.1"

[[audits.p256]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
version = "0.13.2"

[[audits.p256k1]]
who = "cylewitruk <cyle.witruk@outlook.com>"
criteria = "safe-to-deploy"
version = "7.2.2"
notes = "This change only adds wrapping to some additional bindings so that they get mangled and avoid linking errors."

[[audits.password-hash]]
who = "viktar <mcviktor@tut.by"
criteria = "safe-to-deploy"
version = "0.5.0"

[[audits.primeorder]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
version = "0.13.6"

[[audits.quinn-proto]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.11.9 -> 0.11.14"

[[audits.rand_xoshiro]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.6.0 -> 0.7.0"

[[audits.serdect]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
version = "0.2.0"

[[audits.stacks-common]]
who = "cylewitruk <cyle.witruk@outlook.com>"
criteria = "safe-to-deploy"
version = "0.0.1"
notes = "I did not fully review the changes in this diff -- they are Stacks-internal."

[[audits.stacks-common]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.0.1 -> 0.0.1@git:1cba695b09690790b1220b0f5d149f70f78ddea5"
importable = false

[[audits.webpki-roots]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
version = "0.25.4"

[[audits.wsts]]
who = "cylewitruk <cyle.witruk@outlook.com>"
criteria = "safe-to-deploy"
version = "10.0.0"

[[audits.wsts]]
who = "xoloki <xoloki@gmail.com>"
criteria = "safe-to-deploy"
version = "13.0.0"

[[audits.wsts]]
who = "xoloki <xoloki@gmail.com>"
criteria = "safe-to-deploy"
version = "13.0.1"

[[audits.wsts]]
who = "xoloki <xoloki@gmail.com>"
criteria = "safe-to-deploy"
version = "14.0.0"

[[audits.yamux]]
who = "djordon <dan.jordon@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.13.3 -> 0.13.10"
