x-common-vars:
  # Postgres
  - &POSTGRES_PASSWORD ${POSTGRES_PASSWORD:?} # Required
  - &POSTGRES_DB ${POSTGRES_DB:-signer}
  - &POSTGRES_USER ${POSTGRES_USER:-postgres}
  - &POSTGRES_HOST ${POSTGRES_HOST:-postgres}
  - &POSTGRES_PORT ${POSTGRES_PORT:-5432}
  # Bitcoin RPC
  - &BITCOIN_RPC_USERNAME ${BITCOIN_RPC_USERNAME:?} # Required
  - &BITCOIN_RPC_PASSWORD ${BITCOIN_RPC_PASSWORD:?} # Required
  - &BITCOIN_RPC_HOST ${BITCOIN_RPC_HOST:?} # Required
  - &BITCOIN_RPC_PORT ${BITCOIN_RPC_PORT:-8332}
  # Stacks RPC
  - &STACKS_RPC_HOST ${STACKS_RPC_HOST:?} # Required
  - &STACKS_RPC_PORT ${STACKS_RPC_PORT:-20443}
  # Signer private key
  - &SIGNER_SIGNER__PRIVATE_KEY ${SIGNER_SIGNER__PRIVATE_KEY:?} # Required
  # Emily
  - &EMILY_API_KEY ${EMILY_API_KEY:?} # Required
  # Blocklist client
  - &BLOCKLIST_CLIENT_RISK_ANALYSIS__API_KEY ${BLOCKLIST_CLIENT_RISK_ANALYSIS__API_KEY:?} # Required
  # Vector, Cloudwatch log streaming
  - &STREAM_NAME ${STREAM_NAME:?} # Required
  - &AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID:?} # Required
  - &AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY:?} # Required

services:
  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres:16.6-bookworm@sha256:c965017e1d29eb03e18a11abc25f5e3cd78cb5ac799d495922264b8489d5a3a1
    stop_grace_period: 5s
    environment:
      POSTGRES_DB: *POSTGRES_DB
      POSTGRES_USER: *POSTGRES_USER
      POSTGRES_PASSWORD: *POSTGRES_PASSWORD
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  sbtc-signer:
    container_name: sbtc-signer
    restart: on-failure
    # this version can be outdated, check the last image on: https://github.com/stacks-sbtc/sbtc/pkgs/container/sbtc
    image: ghcr.io/stacks-sbtc/sbtc:signer-v1.0.2@sha256:60832405b3f56e8c8ae9ac9429866ce5173f86ff79652bad7f38481f220b2332
    entrypoint:
      - "/usr/local/bin/signer"
      - "--config"
      - "/signer-config.toml"
      - "--migrate-db"
      - "--output-format"
      - "json"
    depends_on:
      - postgres
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
        tag: "sbtc-signer"
    environment:
      RUST_LOG: info,signer=debug
      SIGNER_BITCOIN__RPC_ENDPOINTS: "http://${BITCOIN_RPC_USERNAME}:${BITCOIN_RPC_PASSWORD}@${BITCOIN_RPC_HOST}:${BITCOIN_RPC_PORT}"
      SIGNER_STACKS__ENDPOINTS: "http://${STACKS_RPC_HOST}:${STACKS_RPC_PORT}"
      SIGNER_SIGNER__PRIVATE_KEY: "${SIGNER_SIGNER__PRIVATE_KEY}"
      SIGNER_EMILY__ENDPOINTS: "https://${EMILY_API_KEY}@sbtc-emily.com"
      SIGNER_SIGNER__DB_ENDPOINT: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    volumes:
      - ./sbtc-signer/signer-config.toml.in:/signer-config.toml:ro
    ports:
      - "4122:4122" # P2P communication between sBTC signers
      - "9184:9184" # Prometheus metrics
      - "127.0.0.1:8801:8801" # this export is only exposed to the Docker host for security reasons. NEVER expose it to the internet!

  blocklist-client:
    restart: on-failure
    container_name: blocklist-client
    # this version can be outdated, check the last image on: https://github.com/stacks-sbtc/sbtc/pkgs/container/sbtc
    image: ghcr.io/stacks-sbtc/sbtc:blocklist-client-v1.0.2@sha256:713a19fc6ad6f3538da7849d8c731f65b1bc0d9258f59947b487087c0c94d4be
    command: "/usr/local/bin/blocklist-client"
    environment:
      BLOCKLIST_CLIENT_RISK_ANALYSIS__API_KEY: *BLOCKLIST_CLIENT_RISK_ANALYSIS__API_KEY
      BLOCKLIST_CLIENT_RISK_ANALYSIS__API_URL: https://public.chainalysis.com
      BLOCKLIST_CLIENT_ASSESSMENT__ASSESSMENT_METHOD: sanctions
      BLOCKLIST_CLIENT_SERVER__HOST: "0.0.0.0"
      BLOCKLIST_CLIENT_SERVER__PORT: "3032"

  vector:
    container_name: vector
    image: timberio/vector:0.44.0-debian@sha256:e285e1543366ac306f3957c25d3aca4d2f86855ae274fa4de3522676d72fa0df
    ports:
      - "127.0.0.1:24224:24224"
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
    environment:
      STREAM_NAME: *STREAM_NAME
      AWS_ACCESS_KEY_ID: *AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: *AWS_SECRET_ACCESS_KEY
      VECTOR_LOG: INFO
