/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DepositWithStatusSchemed : Workaround to make utopia generate openapi. Used only as last step before sending UpdateDepositsResponce
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DepositWithStatusSchemed {
    #[serde(
        rename = "deposit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub deposit: Option<Option<Box<models::Deposit>>>,
    #[serde(
        rename = "error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: u32,
}

impl DepositWithStatusSchemed {
    /// Workaround to make utopia generate openapi. Used only as last step before sending UpdateDepositsResponce
    pub fn new(status: u32) -> DepositWithStatusSchemed {
        DepositWithStatusSchemed {
            deposit: None,
            error: None,
            status,
        }
    }
}
