/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExpectedFulfillmentInfo : Withdrawal parameters.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpectedFulfillmentInfo {
    /// Expected bitcoin block height on which signers will _try_ to fullfill withdrawal request.
    #[serde(
        rename = "expectedHeight",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expected_height: Option<Option<u64>>,
    /// Expected txid of the transaction fullfilling withdrawal request
    #[serde(
        rename = "expectedTxid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expected_txid: Option<Option<String>>,
}

impl ExpectedFulfillmentInfo {
    /// Withdrawal parameters.
    pub fn new() -> ExpectedFulfillmentInfo {
        ExpectedFulfillmentInfo {
            expected_height: None,
            expected_txid: None,
        }
    }
}
