/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SlowdownKey : Represents the slowdown key
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlowdownKey {
    /// The hash of the secret associated with this key.
    #[serde(rename = "hash")]
    pub hash: String,
    /// The name of the key.
    #[serde(rename = "name")]
    pub name: String,
}

impl SlowdownKey {
    /// Represents the slowdown key
    pub fn new(hash: String, name: String) -> SlowdownKey {
        SlowdownKey { hash, name }
    }
}
