/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WithdrawalWithStatus : Wrapper for withdrawal with status code. Used for multi-status responses.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawalWithStatus {
    /// HTTP status code, returned as part of multi-status responses.
    #[serde(rename = "status")]
    pub status: u32,
    #[serde(rename = "withdrawal")]
    pub withdrawal: Box<models::Withdrawal>,
}

impl WithdrawalWithStatus {
    /// Wrapper for withdrawal with status code. Used for multi-status responses.
    pub fn new(status: u32, withdrawal: models::Withdrawal) -> WithdrawalWithStatus {
        WithdrawalWithStatus {
            status,
            withdrawal: Box::new(withdrawal),
        }
    }
}
