/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WithdrawalWithStatus : Wrapper for withdrawal with status code. Used for multi-status responses. TODO: utopia, which we use for generating OpenAPI spec does not support [`Result`] in structs, however, logically exactly one of `withdrawal` or `error` should be None, and exactly one of them should be Some. It would be nice to find a way to use `Result` here.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawalWithStatus {
    /// String explaining error occured during updating the withdrawal.
    #[serde(
        rename = "error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<Option<String>>,
    /// HTTP status code for the withdrawal processing result.
    #[serde(rename = "status")]
    pub status: u32,
    #[serde(
        rename = "withdrawal",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub withdrawal: Option<Option<Box<models::Withdrawal>>>,
}

impl WithdrawalWithStatus {
    /// Wrapper for withdrawal with status code. Used for multi-status responses. TODO: utopia, which we use for generating OpenAPI spec does not support [`Result`] in structs, however, logically exactly one of `withdrawal` or `error` should be None, and exactly one of them should be Some. It would be nice to find a way to use `Result` here.
    pub fn new(status: u32) -> WithdrawalWithStatus {
        WithdrawalWithStatus {
            error: None,
            status,
            withdrawal: None,
        }
    }
}
