## Prometheus Host metrics

[sources.host_metrics]
type = "host_metrics"
collectors = ["cpu", "disk", "load", "filesystem", "host", "memory", "network"]
scrape_interval_secs = 15

[sources.host_metrics.filesystem.mountpoints]
includes = ["/"]

[sources.host_metrics.disk.devices]
includes = ["/dev/root", "nvme*", "tmpfs"]

[sources.app]
type = "prometheus_scrape"
endpoints = [
    "http://sbtc-signer-1:9181",
    "http://sbtc-signer-2:9182",
    "http://sbtc-signer-3:9183",
]
instance_tag = "signer"

## App Metric Sinks

[sinks.host_metrics_sink]
type = "prometheus_exporter"
inputs = ["host_metrics", "app"]
address = "0.0.0.0:9598"


## App Logs

[sources.docker_logs]
type = "docker_logs"
include_containers = [
    "sbtc-signer-1",
    "sbtc-signer-2",
    "sbtc-signer-3",
]

# Reshape the logs produced by the docker source.
#
# If the "message" field is valid JSON, we merge it into the source JSON
# and delete the "message" field. Otherwise, we keep the original "message"
# field. A list of added fields could be found here:
# <https://vector.dev/docs/reference/configuration/sources/docker_logs/#log-fields>.
[transforms.json_messages]
type = "remap"
inputs = ["docker_logs"]
drop_on_error = true
source = '''
.docker_container_created_at = del(.container_created_at)
.docker_container_id = del(.container_id)
.docker_container_name = del(.container_name)
.docker_host = del(.host)
.docker_image = del(.image)
.docker_label = del(.label)

parsed, err = parse_json(.message)
if err == null && is_object(parsed) {
  . = merge(., object!(parsed))
  del(.message)
}
'''

[sinks.loki]
type = "loki"
inputs = [ "json_messages"]
endpoint = "http://loki:3100"
out_of_order_action = "accept"

  [sinks.loki.encoding]
  codec = "json"

  [sinks.loki.labels]
  docker_image = "{{ docker_image }}"
