/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExpectedFulfillmentInfo : Expected information about future fulfillment of the withdrawal. This struct represents _estimate_ of how fulfillment for the withdrawal will look like. This estimation is for reference only, and does not provide any guarantees.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpectedFulfillmentInfo {
    /// The estimated bitcoin block height for the bitcoin block confirming the transaction fulling the withdrawal request. This value is estimated by Emily once when the withdrawal request is initially received.
    #[serde(
        rename = "bitcoinBlockHeight",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub bitcoin_block_height: Option<Option<u64>>,
    /// The expected txid of the sweep transaction fulfilling the withdrawal request. This field is populated once, it is not updated if there is an RBF transaction that also fulfills the request.
    #[serde(
        rename = "bitcoinTxid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub bitcoin_txid: Option<Option<String>>,
}

impl ExpectedFulfillmentInfo {
    /// Expected information about future fulfillment of the withdrawal. This struct represents _estimate_ of how fulfillment for the withdrawal will look like. This estimation is for reference only, and does not provide any guarantees.
    pub fn new() -> ExpectedFulfillmentInfo {
        ExpectedFulfillmentInfo {
            bitcoin_block_height: None,
            bitcoin_txid: None,
        }
    }
}
