/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SlowdownReqwest : Represents the slowdown reqwest
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlowdownReqwest {
    /// The name of the key.
    #[serde(rename = "hash")]
    pub hash: String,
    /// The secret associated with this key.
    #[serde(rename = "secret")]
    pub secret: String,
}

impl SlowdownReqwest {
    /// Represents the slowdown reqwest
    pub fn new(hash: String, secret: String) -> SlowdownReqwest {
        SlowdownReqwest { hash, secret }
    }
}
