# Use the chain <chain> (default: main). Allowed values: main, test,
# signet, regtest
# chain=regtest
regtest=1 #chain=regtest

[regtest]
# Send trace/debug info to console (default: 1 when no -daemon. To disable
# logging to file, set -nodebuglogfile)
printtoconsole=1

# Do not load the wallet and disable wallet RPC calls
disablewallet=0

# Maintain a full transaction index, used by the getrawtransaction rpc
# call (default: 0)
txindex=0

# Reduce storage requirements by enabling pruning (deleting) of old
# blocks. This allows the pruneblockchain RPC to be called to
# delete specific blocks and enables automatic pruning of old
# blocks if a target size in MiB is provided. This mode is
# incompatible with -txindex. Warning: Reverting this setting
# requires re-downloading the entire blockchain. (default: 0 =
# disable pruning blocks, 1 = allow manual pruning via RPC, >=550 =
# automatically prune block files to stay under the specified
# target size in MiB)
prune=1

# Specify a non-default location to store blockchain data.
# blocksdir=/data/bitcoin-data
# Specify a non-default location to store blockchain and other data.
# datadir=/data/bitcoin-data

# [network]
# Bind to given address and always listen on it (default: 0.0.0.0). Use
# [host]:port notation for IPv6. Append =onion to tag any incoming
# connections to that address and port as incoming Tor connections
# (default: 127.0.0.1:8334=onion, testnet: 127.0.0.1:18334=onion,
# signet: 127.0.0.1:38334=onion, regtest: 127.0.0.1:18445=onion)
# bind=0.0.0.0:18444

# Discover own IP addresses (default: 1 when listening and no -externalip
# or -proxy)
discover=0

# Allow DNS lookups for -addnode, -seednode and -connect (default: 1)
dns=0

# Query for peer addresses via DNS lookup, if low on addresses (default: 1
# unless -connect used or -maxconnections=0)
dnsseed=0

# Automatically create Tor onion service (default: 1)
listenonion=0

# [rpc]
rpcserialversion=0
# Accept command line and JSON-RPC commands
server=1
# Accept public REST requests.
rest=1

# Bind to given address to listen for JSON-RPC connections. Do not expose
# the RPC server to untrusted networks such as the public internet!
# This option is ignored unless -rpcallowip is also passed. Port is
# optional and overrides -rpcport. Use [host]:port notation for
# IPv6. This option can be specified multiple times (default:
# 127.0.0.1 and ::1 i.e., localhost)
rpcbind=0.0.0.0:18443

# Allow JSON-RPC connections from specified source. Valid values for <ip>
# are a single IP (e.g. 1.2.3.4), a network/netmask (e.g.
# 1.2.3.4/255.255.255.0), a network/CIDR (e.g. 1.2.3.4/24), all
# ipv4 (0.0.0.0/0), or all ipv6 (::/0). This option can be
# specified multiple times
rpcallowip=0.0.0.0/0
rpcallowip=::/0

# Username for JSON-RPC connections
rpcuser=devnet

# Password for JSON-RPC connections
rpcpassword=devnet

# [wallet]
### Wallet options


# What type of addresses to use ("legacy", "p2sh-segwit", "bech32", or
# "bech32m", default: "bech32")
addresstype=legacy

# What type of change to use ("legacy", "p2sh-segwit", "bech32", or
# "bech32m"). Default is "legacy" when -addresstype=legacy, else it
# is an implementation detail.
changetype=legacy

# A fee rate (in BTC/kvB) that will be used when fee estimation has
# insufficient data. 0 to entirely disable the fallbackfee feature.
# (default: 0.00)
fallbackfee=0.00001
